accounts/urls.py
from django.urls import include, path
from .import views

app_name = 'accounts' 

urlpatterns = [
    path('signup',views.signup, name= 'signup'),
    path('profile',views.profile, name= 'profile'),
    path('profile/edit',views.profile_edit, name= 'profile_edit'),

] 

job/urls.py
from django.urls import path , include
from . import views
from . import api
app_name = 'job'  # name of the app

urlpatterns =[
    path('',views.job_list, name= 'job_list'),
    path('add', views.add_job , name='add_job'),
    path('<str:slug>', views.job_detail , name='job_detail'),

    ## api
    path('api/jobs/', api.job_list_api , name='joblistapi'),
    path('api/jobs/<int:id>', api.job_detail_api , name='job_detail_api'),

    ## CBV
    path('api/v2/jobs/', api.JobListApi.as_view() , name='job_detail_api'),
    path('api/v2/jobs/<int:id>', api.JobDetailApi.as_view() , name='job_detail'),


]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
    
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver




class Profile(models.Model):
    # one to one relationship between user and profile
    user = models.OneToOneField(User,on_delete= models.CASCADE)
    #city
    city = models.ForeignKey('City',related_name='user_city', on_delete= models.CASCADE, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    image = models.ImageField(upload_to='profile/', blank=True, null=True)

    def __str__(self):
        return str(self.user)

## create new user ---> create new profile

@receiver(post_save, sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    
    


class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return str(self.name)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Profile
class SignupForm(UserCreationForm):
    usable_password = None
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'email']



class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_number','image']

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . forms import SignupForm, UserForm, ProfileForm
from django.contrib.auth import authenticate, login
from .models import Profile

def signup(request):

    if request.method == 'POST':
        form  = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/accounts/profile')
    else:
        form = SignupForm()

    return render(request, 'registration/signup.html',{'form':form})



def profile(request):
    profile = Profile.objects.get(user= request.user)
    
    return render(request, 'accounts/profile.html',{'profile':profile})




def profile_edit(request):
    profile = Profile.objects.get(user= request.user)

    if request.method == 'POST':
        userform = UserForm(request.POST,instance = request.user)
        profileform = ProfileForm(request.POST, request.FILES, instance =profile )

        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()

            return redirect(reverse('accounts:profile'))

    else:
        userform = UserForm(instance = request.user)
        profileform = ProfileForm(instance =profile )

    return render(request, 'accounts/profile_edit.html',{'userform':userform, 'profileform':profileform})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job_detail}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">

                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                            </ul>

                        </div>

                        <div class="p-5">
                            
                            <a class="boxed-btn3 w-100"  href="{% url 'accounts:profile_edit' %}">Edit Profile</a>
                        </div>
                        
                    </div>
                  
                </div>
            </div>
        </div>
    </div>

{% endblock body %}


<div class="submit_btn">
    <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
</div>

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job_detail}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job_detail.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form  method="POST", enctype="multipart/form-data">

                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}
                            {% buttons %}
                            <button class="boxed-btn3 w-100" type="submit">Savep</button>
                            {% endbuttons %}

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}